### ISSUE TITLE
Support for importing sub-grammars

### ISSUE THREAD

**Issue by ncalexan** [kevinmehall/rust-peg#191] opened 2018-05-07 16:04 UTC
This is a simplified version of #25.  I'm parsing EDN (https://github.com/edn-format/edn) and specific data structures expressed in EDN.  Equivalently, I'm first parsing Lisp, say, and then parsing some specific Lisp constructs like `defun` or `loop`.  I'm parsing more than one specific type of data structure.

What I'd like to be able to do is define the "EDN part" of the parser and then use that EDN part in multiple other parsers that build on it.  So:
- `edn.rustpeg` defines `pub value -> edn::Value`
- `query.rustpeg` includes `edn.rustpeg` and defines
```
pub query -> Query =
  "query" q:(value) { ... }
```
- similarly for `transact.rustpeg`

I would be happy for this to work like concatenation (so: no code-sharing), and I think I could achieve this manually in my `build.rs` buildscript.  (The tricky piece is arranging for the `use ...` statements to not conflict.  I'm mostly happy to take on that responsibility as a consumer.)

It would be nice for there to be only one compiled version of the underlying EDN `value` parser, but I'm not sure that's easy, due to the consumer controlling the name of the module that imports the EDN parser Rust code.  But again, I'm happy for the consumer to own naming and collision avoidance.

So, before I go hack this into my buildscript, am I missing something that would make this easy?  Hard?  Is this more generally useful?

**Comment by kevinmehall** [comment] 2018-05-20 22:40
You're right, `include!()`-style importing would sidestep a lot of the complexity. One concern I have is that it doesn't play well with Cargo because you have to point to the file by filesystem path, thus it would be difficult to re-use code from another crate. That said, I wouldn't be opposed to a PR implementing this.

I've also been thinking about another way of getting reusability without adding a lot of single-purpose syntax -- exposing just a few more bits of the parser internals such that action code written in Rust can serve as the glue to integrate with another parser, whether implemented in rust-peg or otherwise. Essentially this would be an extended form of the `{? ...}` syntax that is given access to the unparsed remainder of the input string and decides if it matches and how much of it to consume. That, along with the ability for the public API of a parser to match a prefix of the input (#179), would allow one grammar to import and call into another, purely at the Rust API level. It's a bit of an open question how much of the error handling internals it would be worth exposing for this, though.

Do either of these stand out as more suitable for Mentat's use case?

**Comment by kevinmehall** [comment] 2019-10-06 21:56
With the switch to a procedural macro in [0.6](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0), I don't think the `include!()` approach is viable anymore since the grammar is embedded in a Rust source file and the meta-grammar is defined in terms of Rust `TokenTree`. Therefore, closing this as a duplicate of #25; we'll have to figure out a good way to do it at the Rust level.

p.s. Sad to see that Mentat was canceled. :cry:

**Closed** 2019-10-06 21:56 UTC
Labels: enhancement

**Comment by ncalexan** [comment] 2019-10-07 22:30
> With the switch to a procedural macro in [0.6](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0), I don't think the `include!()` approach is viable anymore since the grammar is embedded in a Rust source file and the meta-grammar is defined in terms of Rust `TokenTree`. Therefore, closing this as a duplicate of #25; we'll have to figure out a good way to do it at the Rust level.

Thanks for updating the ticket.

> p.s. Sad to see that Mentat was canceled. 😢

Yeah, there were some interesting ideas in the project.  The good news is that a lot of the cross-platform architecture around Rust lives on in the [Rust Firefox Sync implementation](https://github.com/mozilla/application-services).  Take care!
