### ISSUE TITLE
Allow 'input lifetime parameter for token definitions.

### ISSUE THREAD

**Issue by sandeep-datta** [kevinmehall/rust-peg#270] opened 2021-09-04 19:52 UTC
Note the following code does not compile because of `'input`. Please consider allowing this use case.

```
#[derive(Clone)]
pub enum Token<'input> {
    Open,
    Number(i32),
    Comma,
    Close,
    Ident(&'input str)
}

peg::parser!{
    grammar tokenparser() for [Token<'input>] {
          ...
    }
}
```

**Comment by kevinmehall** [comment] 2021-09-04 20:14
I think this was fixed by #254 -- does this work?

```rs
peg::parser!{
    grammar tokenparser<'a>() for [Token<'a>] {
          ...
    }
}
```

**Comment by sandeep-datta** [comment] 2021-09-04 21:10
It just creates a separate lifetime ...
`
pub fn module_traced<'input, 'a>(__input: &'input Input<'a>, module_name: &str) -> ::std::result::Result<Ast<'input>, ::peg::error::ParseError<PositionRepr<'a>>>`

**Comment by kevinmehall** [comment] 2021-09-04 21:25
Hmm, so the problem is that you want to produce a result containing `&'input Token<'a>` without requiring the result type to have both lifetime params?

Ideally I'd like to get rid of the magic `'input` lifetime since hard-coding a name violates macro hygiene and reduces flexibility in places like this, but I'm not sure how to do it without fully exposing the `&'input` part of the input type and making everyone write  `grammar foo<'input> for &'input str` for the common case.

**Comment by sandeep-datta** [comment] 2021-09-05 06:49
I might have had a brief mental lapse here. I conflated the lifetime of the token stream with the lifetime of the string used to generate it.

Regardless, I like your explicit lifetime syntax. Maybe you can elide the lifetime when the grammar does not reference it?

**Closed** 2021-09-05 08:14 UTC
