### ISSUE TITLE
Redox OS - "error: Could not compile `peg`."

### ISSUE THREAD

**Issue by k-wax** [kevinmehall/rust-peg#132] opened 2016-04-26 20:29 UTC
arch linux, rust-git, multirust-git
trying to install using https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh

make all fails with the following error:

   Compiling peg v0.3.9 (https://github.com/crazymykl/rust-peg.git?branch=libsyntax-changes-again#1efaca63)
     Running `./rustc-i386.sh /home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/peg_syntax_ext.rs --crate-name peg_syntax_ext --crate-type dylib -C prefer-dynamic -g -C metadata=f8d111835d3afa96 -C extra-filename=-f8d111835d3afa96 --out-dir /home/kwax/build/redox/redox/build/debug/deps --emit=dep-info,link -L dependency=/home/kwax/build/redox/redox/build/debug/deps -L dependency=/home/kwax/build/redox/redox/build/debug/deps --cap-lints allow`
   Compiling glob v0.2.11
     Running `./rustc-i386.sh /home/kwax/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/glob-0.2.11/src/lib.rs --crate-name glob --crate-type lib -g -C metadata=0ffe4874535835d5 -C extra-filename=-0ffe4874535835d5 --out-dir /home/kwax/build/redox/redox/build/i386-unknown-redox/debug/deps --emit=dep-info,link --target i386-unknown-redox.json -L dependency=/home/kwax/build/redox/redox/build/i386-unknown-redox/debug/deps -L dependency=/home/kwax/build/redox/redox/build/i386-unknown-redox/debug/deps --cap-lints allow`
/home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/rustast.rs:21:33: 21:70 error: unresolved name `syntax::parse::parser::NoTypesAllowed` [E0425]
/home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/rustast.rs:21 	let r = panictry!(p.parse_path(syntax::parse::parser::NoTypesAllowed));
                                                                                                                                 	                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/rustast.rs:21:33: 21:70 note: in this expansion of panictry! (defined in <syntax macros>)
/home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/rustast.rs:21:33: 21:70 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `peg`.

Caused by:
  Process didn't exit successfully: `./rustc-i386.sh /home/kwax/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/peg_syntax_ext.rs --crate-name peg_syntax_ext --crate-type dylib -C prefer-dynamic -g -C metadata=f8d111835d3afa96 -C extra-filename=-f8d111835d3afa96 --out-dir /home/kwax/build/redox/redox/build/debug/deps --emit=dep-info,link -L dependency=/home/kwax/build/redox/redox/build/debug/deps -L dependency=/home/kwax/build/redox/redox/build/debug/deps --cap-lints allow` (exit code: 101)
Makefile:236: recipe for target 'build/i386-unknown-redox/debug/ion-shell.bin' failed
make: *** [build/i386-unknown-redox/debug/ion-shell.bin] Error 101

**Comment by kevinmehall** [comment] 2016-04-26 20:33
Duplicate of #131; fixed in 0.3.11

**Closed by kevinmehall** 2016-04-26 20:33 UTC
