### ISSUE TITLE
Capture both details and full input

### ISSUE THREAD

**Issue by chrysn** [kevinmehall/rust-peg#377] opened 2024-06-10 10:19 UTC
For an aspect of parsing CBOR with the peg crate, I find myself in need to capture in a single rule both details and the full input, because the parser output gets post-processed differently. In a simplified example:

```rust
    pub rule basenumber() -> NumberParts<'input>
        = sign:sign()? "0" parts:(
                            / ['x'|'X'] "." postdot:$(HEXDIG()+) ['p'|'P'] expsign:sign()? exp:$(DIGIT()+)
                              { (16, "", Some(postdot), expsign, Some(exp)) }
                            / ['o'|'O'] predot:$(ODIGIT()+)
                              { (8, predot, None, None, None) }
                            / /.../
            )
        {
            let (base, predot, postdot, expsign, exp) = parts;
            NumberParts {
                base,
                sign,
                /.../,
                // would like to have the full input here as well
            }
        }
```

It would be convenient to write

```rust
        = full:$(sign:sign()? "0" parts:( /.../ )) {
            NumberParts {
                base,
                sign,
                /.../,
                full,
            }
        }
```

but then I can *only* get access to the `full` result and not to `sign` any more.

Is there an existing trick I'm missing, or could this be made available in a compatible way, eg. by providing a part's inner variables transparently by declaring them in the generated code, such that they might be shadowed by the outer assignments?

**Comment by kevinmehall** [comment] 2024-06-10 15:29
Duplicate of https://github.com/kevinmehall/rust-peg/issues/283, which has a workaround in the comments.

**Closed by kevinmehall** 2024-06-10 15:29 UTC
